//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fonctionnalite
    {
        public Fonctionnalite()
        {
            this.Scenarios = new HashSet<Scenario>();
            this.ScenarioContext = new HashSet<Scenario>();
            this.Tags = new HashSet<Tag>();
        }
    
        public System.Guid Id { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public string TestResult { get; set; }
        public System.Guid ProjetId { get; set; }
    
        public virtual ICollection<Scenario> Scenarios { get; set; }
        public virtual ICollection<Scenario> ScenarioContext { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual Projet Projet { get; set; }
    }
}
