//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        public Projet()
        {
            this.Fonctionnalites = new HashSet<Fonctionnalite>();
        }
    
        public System.Guid Id { get; set; }
        public string Nom { get; set; }
        public string Version { get; set; }
        public string PathToFeatures { get; set; }
        public string PathToTestDll { get; set; }
        public string PathToTestSettings { get; set; }
    
        public virtual ICollection<Fonctionnalite> Fonctionnalites { get; set; }
    }
}
