//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenario
    {
        public Scenario()
        {
            this.Etapes = new HashSet<Etape>();
            this.Tags = new HashSet<Tag>();
            this.TestInfos = new HashSet<TestInfo>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> FonctionnaliteId { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> Fonctionnalite1_Id { get; set; }
    
        public virtual ICollection<Etape> Etapes { get; set; }
        public virtual Fonctionnalite Fonctionnalite { get; set; }
        public virtual Fonctionnalite Fonctionnalite1 { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<TestInfo> TestInfos { get; set; }
    }
}
