//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.Etapes = new HashSet<Etape>();
            this.TableRows = new HashSet<TableRow>();
            this.TableHeader = new HashSet<TableRow>();
        }
    
        public System.Guid Id { get; set; }
    
        public virtual ICollection<Etape> Etapes { get; set; }
        public virtual ICollection<TableRow> TableRows { get; set; }
        public virtual ICollection<TableRow> TableHeader { get; set; }
    }
}
