//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableRow
    {
        public TableRow()
        {
            this.TableColonnes = new HashSet<TableColonne>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TableId { get; set; }
        public Nullable<System.Guid> TableHeader_Id { get; set; }
        public int RowIndex { get; set; }
    
        public virtual ICollection<TableColonne> TableColonnes { get; set; }
        public virtual Table Table { get; set; }
        public virtual Table Table1 { get; set; }
    }
}
