//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableColonne
    {
        public System.Guid Id { get; set; }
        public string Valeur { get; set; }
        public System.Guid TableRowId { get; set; }
        public int ColIndex { get; set; }
    
        public virtual TableRow TableRow { get; set; }
    }
}
