//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public System.Guid Id { get; set; }
        public string TagName { get; set; }
        public Nullable<System.Guid> ScenarioId { get; set; }
        public Nullable<System.Guid> FonctionnaliteId { get; set; }
    
        public virtual Fonctionnalite Fonctionnalite { get; set; }
        public virtual Scenario Scenario { get; set; }
    }
}
